DROP TABLE POPULARITY CASCADE CONSTRAINTS;
DROP TABLE FOOD CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE COOKING CASCADE CONSTRAINTS;
DROP TABLE NATION CASCADE CONSTRAINTS;
DROP SEQUENCE MEMBERSEQ;

CREATE SEQUENCE MEMBERSEQ START WITH 11 NOCACHE;

CREATE TABLE NATION(
   NATION_ID VARCHAR2(10) PRIMARY KEY,
   NATION VARCHAR2(50) NOT NULL
);

INSERT INTO NATION VALUES('N1','한식');
INSERT INTO NATION VALUES('N2','중식');
INSERT INTO NATION VALUES('N3','일식');
INSERT INTO NATION VALUES('N4','멕시칸/양식');
INSERT INTO NATION VALUES('N5','퓨전');
INSERT INTO NATION VALUES('N6','동남아/인도네시아');

SELECT * FROM NATION ;


CREATE TABLE COOKING(
   COOKING_ID VARCHAR2(10) PRIMARY KEY,
   COOKING VARCHAR2(50) NOT NULL
);
INSERT INTO COOKING VALUES('C1','밥');
INSERT INTO COOKING VALUES('C2','면');
INSERT INTO COOKING VALUES('C3','국물');
INSERT INTO COOKING VALUES('C4','찜/조림');
INSERT INTO COOKING VALUES('C5','구이');
INSERT INTO COOKING VALUES('C6','볶음');
INSERT INTO COOKING VALUES('C7','튀김');
INSERT INTO COOKING VALUES('C8','나물/샐러드');
INSERT INTO COOKING VALUES('C9','김장/절임');
INSERT INTO COOKING VALUES('C10','베이킹/디저트');
INSERT INTO COOKING VALUES('C11','음료/차/커피');

SELECT * FROM COOKING;

CREATE TABLE FOOD(
   F_NO NUMBER PRIMARY KEY,
   F_NAME VARCHAR2(50) NOT NULL,
   NATION_ID VARCHAR2(10) NOT NULL,
   COOKING_ID VARCHAR2(10) NOT NULL,
   RECIPE VARCHAR2(4000) NOT NULL,
   INGREDIENTS VARCHAR2(4000) NOT NULL,
   IMGDIR VARCHAR2(4000) NOT NULL,
   CONSTRAINT FK_NATION FOREIGN KEY (NATION_ID) REFERENCES NATION(NATION_ID)
   ON DELETE SET NULL,
   CONSTRAINT FK_COOKING FOREIGN KEY (COOKING_ID) REFERENCES COOKING(COOKING_ID)
   ON DELETE SET NULL
);



CREATE TABLE MEMBER(
   M_NO NUMBER PRIMARY KEY,
   M_ID VARCHAR2(50) NOT NULL UNIQUE,
   M_PW   VARCHAR2(50) NOT NULL,
   M_NAME VARCHAR2(30) NOT NULL,
   PHONE VARCHAR2(15) NOT NULL,
   AGE NUMBER NOT NULL,
   GENDER VARCHAR2(3) NOT NULL,
   RESIDENCE VARCHAR2(100) NOT NULL,
   CONSTRAINT CK_GENDER CHECK(GENDER IN('M','F'))
);

CREATE TABLE POPULARITY(
   F_NO NUMBER NOT NULL,
   M_NO NUMBER NOT NULL,
   M_AGE NUMBER NOT NULL,
   M_GENDER VARCHAR2(3) NOT NULL,
   CONSTRAINT PK_POPULARITY PRIMARY KEY (F_NO,M_NO),
   CONSTRAINT FK_POPULARITY_FN FOREIGN KEY (F_NO) REFERENCES FOOD(F_NO)
   ON DELETE CASCADE,
   CONSTRAINT FK_POPULARITY_MN FOREIGN KEY (M_NO) REFERENCES MEMBER(M_NO)
   ON DELETE CASCADE   
);


SELECT * FROM MEMBER ;
SELECT * FROM POPULARITY ;
SELECT * FROM FOOD;
SELECT * FROM NATION;
SELECT * FROM POPULARITY ;



INSERT INTO POPULARITY VALUES('2','1','27','M');
INSERT INTO POPULARITY VALUES('43','2','28','F');
INSERT INTO POPULARITY VALUES('24','3','30','M');
INSERT INTO POPULARITY VALUES('13','4','33','M');
INSERT INTO POPULARITY VALUES('2','5','45','F');
INSERT INTO POPULARITY VALUES('2','6','67','F');
INSERT INTO POPULARITY VALUES('1','7','55','M');
INSERT INTO POPULARITY VALUES('1','8','19','M');
INSERT INTO POPULARITY VALUES('1','9','22','F');
INSERT INTO POPULARITY VALUES('2','10','35','M');

INSERT INTO POPULARITY VALUES('3','1','27','M');
INSERT INTO POPULARITY VALUES('3','2','28','F');
INSERT INTO POPULARITY VALUES('1','3','30','M');
INSERT INTO POPULARITY VALUES('1','4','33','M');
INSERT INTO POPULARITY VALUES('3','5','45','F');
INSERT INTO POPULARITY VALUES('3','6','67','F');
INSERT INTO POPULARITY VALUES('16','7','55','M');
INSERT INTO POPULARITY VALUES('17','8','19','M');
INSERT INTO POPULARITY VALUES('18','9','22','F');
INSERT INTO POPULARITY VALUES('20','10','35','M');

INSERT INTO POPULARITY VALUES('16','1','27','M');
INSERT INTO POPULARITY VALUES('26','2','28','F');
INSERT INTO POPULARITY VALUES('36','3','30','M');
INSERT INTO POPULARITY VALUES('46','4','33','M');
INSERT INTO POPULARITY VALUES('34','5','45','F');
INSERT INTO POPULARITY VALUES('21','6','67','F');
INSERT INTO POPULARITY VALUES('31','7','55','M');
INSERT INTO POPULARITY VALUES('42','8','19','M');
INSERT INTO POPULARITY VALUES('9','9','22','F');
INSERT INTO POPULARITY VALUES('11','10','35','M');

INSERT INTO POPULARITY VALUES('23','1','27','M');
INSERT INTO POPULARITY VALUES('23','2','28','F');
INSERT INTO POPULARITY VALUES('33','3','30','M');
INSERT INTO POPULARITY VALUES('31','4','33','M');
INSERT INTO POPULARITY VALUES('24','5','45','F');
INSERT INTO POPULARITY VALUES('24','6','67','F');
INSERT INTO POPULARITY VALUES('44','7','55','M');
INSERT INTO POPULARITY VALUES('44','8','19','M');
INSERT INTO POPULARITY VALUES('49','9','22','F');
INSERT INTO POPULARITY VALUES('31','10','35','M');

INSERT INTO POPULARITY VALUES('7','1','27','M');
INSERT INTO POPULARITY VALUES('7','2','28','F');
INSERT INTO POPULARITY VALUES('7','3','30','M');
INSERT INTO POPULARITY VALUES('7','4','33','M');
INSERT INTO POPULARITY VALUES('8','5','45','F');
INSERT INTO POPULARITY VALUES('8','6','67','F');
INSERT INTO POPULARITY VALUES('8','7','55','M');
INSERT INTO POPULARITY VALUES('30','8','19','M');
INSERT INTO POPULARITY VALUES('20','9','22','F');
INSERT INTO POPULARITY VALUES('40','10','35','M');

INSERT INTO POPULARITY VALUES('48','1','27','M');
INSERT INTO POPULARITY VALUES('44','2','28','F');
INSERT INTO POPULARITY VALUES('41','3','30','M');
INSERT INTO POPULARITY VALUES('39','4','33','M');
INSERT INTO POPULARITY VALUES('29','5','45','F');
INSERT INTO POPULARITY VALUES('28','6','67','F');
INSERT INTO POPULARITY VALUES('41','7','55','M');
INSERT INTO POPULARITY VALUES('15','8','19','M');
INSERT INTO POPULARITY VALUES('15','9','22','F');
INSERT INTO POPULARITY VALUES('15','10','35','M');

INSERT INTO POPULARITY VALUES('49','1','27','M');
INSERT INTO POPULARITY VALUES('49','2','28','F');
INSERT INTO POPULARITY VALUES('49','3','30','M');
INSERT INTO POPULARITY VALUES('30','4','33','M');
INSERT INTO POPULARITY VALUES('32','5','45','F');
INSERT INTO POPULARITY VALUES('12','6','67','F');
INSERT INTO POPULARITY VALUES('12','7','55','M');
INSERT INTO POPULARITY VALUES('41','8','19','M');
INSERT INTO POPULARITY VALUES('11','9','22','F');
INSERT INTO POPULARITY VALUES('19','10','35','M');

INSERT INTO POPULARITY VALUES('25','1','27','M');
INSERT INTO POPULARITY VALUES('19','2','28','F');
INSERT INTO POPULARITY VALUES('50','3','30','M');
INSERT INTO POPULARITY VALUES('50','4','33','M');
INSERT INTO POPULARITY VALUES('17','5','45','F');
INSERT INTO POPULARITY VALUES('43','6','67','F');
INSERT INTO POPULARITY VALUES('21','7','55','M');
INSERT INTO POPULARITY VALUES('38','8','19','M');
INSERT INTO POPULARITY VALUES('42','9','22','F');


SELECT * FROM POPULARITY p;